# Generated by Django 5.2.10 on 2026-05-21 07:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0002_initial'),
        ('db_query_history', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryExecutionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('mongodb', 'MongoDB'), ('sqlite', 'SQLite'), ('sqlserver', 'SQL Server'), ('mariadb', 'MariaDB'), ('cockroachdb', 'CockroachDB')], max_length=30)),
                ('plan_text', models.TextField(help_text='Raw EXPLAIN / aggregation output')),
                ('parsed_plan', models.JSONField(blank=True, default=dict, help_text='Structured JSON representation of the plan steps')),
                ('total_cost', models.FloatField(default=0, help_text='Estimated or actual plan cost')),
                ('execution_time_ms', models.FloatField(default=0, help_text='ANALYZE-reported actual execution time in ms')),
                ('rows_examined', models.BigIntegerField(default=0)),
                ('rows_returned', models.BigIntegerField(default=0)),
                ('indexes_used', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the normalised query text (dedup/grouping)', max_length=64)),
                ('engine', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('mongodb', 'MongoDB'), ('sqlite', 'SQLite'), ('sqlserver', 'SQL Server'), ('mariadb', 'MariaDB'), ('cockroachdb', 'CockroachDB')], db_index=True, max_length=30)),
                ('query_type', models.CharField(default='other', max_length=20)),
                ('query_text', models.TextField(help_text='Truncated query text; full text purged by cleanup policy')),
                ('query_label', models.CharField(blank=True, help_text='Auto-labelled from query builder SavedQuery name', max_length=255)),
                ('duration_ms', models.FloatField(db_index=True, default=0)),
                ('rows_affected', models.BigIntegerField(default=0)),
                ('memory_consumed_mb', models.FloatField(default=0)),
                ('cpu_percent', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical'), ('error', 'Error')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_slow', models.BooleanField(db_index=True, default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_metrics', to='connections.databaseconnection')),
                ('execution_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='query_analytics.queryexecutionplan')),
                ('query_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_metrics', to='db_query_history.queryhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('winner_engine', models.CharField(blank=True, choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('mongodb', 'MongoDB'), ('sqlite', 'SQLite'), ('sqlserver', 'SQL Server'), ('mariadb', 'MariaDB'), ('cockroachdb', 'CockroachDB')], max_length=30)),
                ('winner_reason', models.CharField(blank=True, default='', max_length=255)),
                ('fastest_duration_ms', models.FloatField(default=0)),
                ('slowest_duration_ms', models.FloatField(default=0)),
                ('avg_duration_ms', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_comparisons', to=settings.AUTH_USER_MODEL)),
                ('metrics', models.ManyToManyField(blank=True, related_name='comparisons', to='query_analytics.querymetric')),
            ],
            options={
                'verbose_name': 'Query Comparison',
                'verbose_name_plural': 'Query Comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlowQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_hash', models.CharField(db_index=True, max_length=64)),
                ('query_text', models.TextField()),
                ('query_type', models.CharField(default='other', max_length=20)),
                ('engine', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('mongodb', 'MongoDB'), ('sqlite', 'SQLite'), ('sqlserver', 'SQL Server'), ('mariadb', 'MariaDB'), ('cockroachdb', 'CockroachDB')], max_length=30)),
                ('avg_duration_ms', models.FloatField(default=0)),
                ('max_duration_ms', models.FloatField(default=0)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='active', max_length=20)),
                ('threshold_ms', models.FloatField(default=500, help_text='Threshold in effect when this was flagged')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slow_queries', to='connections.databaseconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slow_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='QueryOptimizationSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('mongodb', 'MongoDB'), ('sqlite', 'SQLite'), ('sqlserver', 'SQL Server'), ('mariadb', 'MariaDB'), ('cockroachdb', 'CockroachDB')], max_length=30)),
                ('suggestion_type', models.CharField(blank=True, help_text='e.g. missing_index, unnecessary_join, subquery_extraction, join_reorder, aggregation_pushdown, limit_early', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True, help_text='Why this change improves performance')),
                ('estimated_improvement_pct', models.FloatField(default=0, help_text='Estimated speed-up percentage')),
                ('original_query', models.TextField(blank=True)),
                ('optimized_query', models.TextField(blank=True)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimization_suggestions', to='query_analytics.queryexecutionplan')),
                ('query_metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimization_suggestions', to='query_analytics.querymetric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_suggestions', to=settings.AUTH_USER_MODEL)),
                ('slow_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimization_suggestions', to='query_analytics.slowquery')),
            ],
            options={
                'ordering': ['-estimated_improvement_pct', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndexRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('mongodb', 'MongoDB'), ('sqlite', 'SQLite'), ('sqlserver', 'SQL Server'), ('mariadb', 'MariaDB'), ('cockroachdb', 'CockroachDB')], max_length=30)),
                ('table_name', models.CharField(max_length=255)),
                ('schema_name', models.CharField(blank=True, default='', max_length=255)),
                ('column_names', models.JSONField(blank=True, default=list, help_text='List of columns to index')),
                ('index_type', models.CharField(choices=[('b_tree', 'B-Tree'), ('hash', 'Hash'), ('gist', 'GiST'), ('gin', 'GIN'), ('bitmap', 'Bitmap'), ('innodb', 'InnoDB'), ('myisam', 'MyISAM'), ('hash_mysql', 'Hash (MySQL)')], default='b_tree', max_length=30)),
                ('index_name_suggestion', models.CharField(blank=True, max_length=255)),
                ('create_statement', models.TextField(help_text='Ready-to-run CREATE INDEX statement')),
                ('score', models.FloatField(default=0, help_text='0–100 estimated performance improvement score')),
                ('estimated_improvement_pct', models.FloatField(default=0, help_text='Estimated execution-time reduction as a percentage')),
                ('rationale', models.TextField(blank=True, help_text='Natural-language explanation of why the index helps')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_reason', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_recommendations', to='connections.databaseconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_recommendations', to=settings.AUTH_USER_MODEL)),
                ('slow_queries', models.ManyToManyField(blank=True, related_name='recommendations', to='query_analytics.slowquery')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('active_connections', models.IntegerField(default=0)),
                ('idle_connections', models.IntegerField(default=0)),
                ('total_connections', models.IntegerField(default=0)),
                ('max_capacity', models.IntegerField(default=100)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('active', 'Active'), ('busy', 'Busy'), ('saturated', 'Saturated')], default='idle', max_length=20)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_pool_metrics', to='connections.databaseconnection')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['connection', '-timestamp'], name='query_analy_connect_c7c00a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('mongodb', 'MongoDB'), ('sqlite', 'SQLite'), ('sqlserver', 'SQL Server'), ('mariadb', 'MariaDB'), ('cockroachdb', 'CockroachDB')], max_length=30)),
                ('granularity', models.CharField(choices=[('1m', '1 min'), ('5m', '5 min'), ('15m', '15 min'), ('1h', '1 hour'), ('1d', '1 day')], default='5m', max_length=10)),
                ('bucket_start', models.DateTimeField(db_index=True)),
                ('avg_duration_ms', models.FloatField(default=0)),
                ('max_duration_ms', models.FloatField(default=0)),
                ('min_duration_ms', models.FloatField(default=0)),
                ('p95_duration_ms', models.FloatField(default=0)),
                ('p99_duration_ms', models.FloatField(default=0)),
                ('query_count', models.IntegerField(default=0)),
                ('total_rows', models.BigIntegerField(default=0)),
                ('avg_memory_mb', models.FloatField(default=0)),
                ('avg_cpu_pct', models.FloatField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('slow_query_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_aggregates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bucket_start'],
                'indexes': [models.Index(fields=['user', 'engine', '-bucket_start'], name='query_analy_user_id_617dfb_idx')],
                'unique_together': {('user', 'engine', 'granularity', 'bucket_start')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(blank=True, help_text='e.g. cpu_spike, memory_pressure, pool_saturation, long_transaction', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('metric_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of metrics at alert time')),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_alerts', to='connections.databaseconnection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='query_analy_user_id_bcc5ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_hash', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('engine', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('mongodb', 'MongoDB'), ('sqlite', 'SQLite'), ('sqlserver', 'SQL Server'), ('mariadb', 'MariaDB'), ('cockroachdb', 'CockroachDB')], max_length=30)),
                ('is_favorite', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_labels', to='connections.databaseconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_favorite', '-updated_at'],
                'unique_together': {('user', 'normalized_hash')},
            },
        ),
        migrations.AddIndex(
            model_name='querymetric',
            index=models.Index(fields=['user', '-executed_at'], name='query_analy_user_id_97b77b_idx'),
        ),
        migrations.AddIndex(
            model_name='querymetric',
            index=models.Index(fields=['engine', '-executed_at'], name='query_analy_engine_64d1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='querymetric',
            index=models.Index(fields=['is_slow', '-executed_at'], name='query_analy_is_slow_056db4_idx'),
        ),
        migrations.AddIndex(
            model_name='querymetric',
            index=models.Index(fields=['normalized_hash', 'user'], name='query_analy_normali_e00049_idx'),
        ),
        migrations.AddIndex(
            model_name='querymetric',
            index=models.Index(fields=['connection', '-executed_at'], name='query_analy_connect_b2b9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='slowquery',
            index=models.Index(fields=['user', 'status', '-last_seen'], name='query_analy_user_id_5c3577_idx'),
        ),
        migrations.AddIndex(
            model_name='slowquery',
            index=models.Index(fields=['normalized_hash'], name='query_analy_normali_ec0ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='queryoptimizationsuggestion',
            index=models.Index(fields=['user', 'engine'], name='query_analy_user_id_5c1937_idx'),
        ),
        migrations.AddIndex(
            model_name='indexrecommendation',
            index=models.Index(fields=['user', 'status'], name='query_analy_user_id_062d05_idx'),
        ),
        migrations.AddIndex(
            model_name='indexrecommendation',
            index=models.Index(fields=['engine', 'table_name'], name='query_analy_engine_8ad308_idx'),
        ),
    ]
