# Generated by Django 5.2.10 on 2026-05-21 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStoragePointModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('engine', models.CharField(blank=True, max_length=50)),
                ('table_schema', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('size', models.FloatField(default=0)),
                ('table_size', models.FloatField(default=0)),
                ('total_size', models.FloatField(default=0)),
                ('index_size', models.FloatField(default=0)),
                ('row_count', models.BigIntegerField(default=0)),
                ('live_rows_estimate', models.FloatField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManagedDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('engine', models.CharField(default='postgresql', max_length=50)),
                ('type', models.CharField(choices=[('table', 'Table'), ('view', 'View'), ('materialized_view', 'Materialized View'), ('function', 'Function'), ('procedure', 'Procedure'), ('schema', 'Schema'), ('database', 'Database')], default='table', max_length=30)),
                ('table_schema', models.CharField(blank=True, max_length=100)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('size', models.FloatField(default=0)),
                ('total_size', models.FloatField(default=0)),
                ('table_size', models.FloatField(default=0)),
                ('index_size', models.FloatField(default=0)),
                ('row_count', models.BigIntegerField(default=0)),
                ('live_rows_estimate', models.FloatField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
