# Generated by Django 5.2.10 on 2026-05-21 07:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0002_initial'),
        ('databases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('query_type', models.CharField(choices=[('select', 'SELECT'), ('insert', 'INSERT'), ('update', 'UPDATE'), ('delete', 'DELETE'), ('create', 'CREATE'), ('drop', 'DROP'), ('alter', 'ALTER'), ('other', 'OTHER')], default='other', max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('execution_time', models.FloatField(default=0)),
                ('affected_rows', models.BigIntegerField(default=0)),
                ('result_columns', models.JSONField(blank=True, default=list)),
                ('result_preview', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('has_data', models.BooleanField(default=False)),
                ('row_count', models.BigIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_duration', models.FloatField(default=0)),
                ('auto_discovered_schema', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('has_error', models.BooleanField(default=False)),
                ('column_names', models.JSONField(blank=True, default=list)),
                ('human_readable_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.databaseconnection')),
                ('database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databases.manageddatabase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Query History',
                'verbose_name_plural': 'Query History',
                'ordering': ['-completed_at'],
            },
        ),
    ]
