# Generated by Django 5.2.10 on 2026-05-21 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('engine', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('mongodb', 'MongoDB'), ('sqlite', 'SQLite'), ('sqlserver', 'SQL Server'), ('mariadb', 'MariaDB'), ('cockroachdb', 'CockroachDB')], max_length=30)),
                ('host', models.CharField(default='localhost', max_length=255)),
                ('port', models.IntegerField(default=3306)),
                ('dbname', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.TextField(blank=True, help_text='Encrypted database password')),
                ('options', models.JSONField(blank=True, default=dict)),
                ('query_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('engine', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('mongodb', 'MongoDB'), ('sqlite', 'SQLite'), ('sqlserver', 'SQL Server'), ('mariadb', 'MariaDB'), ('cockroachdb', 'CockroachDB')], max_length=30)),
                ('host', models.CharField(default='localhost', max_length=255)),
                ('port', models.IntegerField(default=3306)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
