# Generated by Django 5.2.10 on 2026-05-21 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_column', models.CharField(max_length=255)),
                ('target_column', models.CharField(max_length=255)),
                ('relation_type', models.CharField(choices=[('one_to_one', 'One-to-One'), ('one_to_many', 'One-to-Many'), ('many_to_many', 'Many-to-Many')], default='one_to_many', max_length=20)),
                ('on_delete', models.CharField(default='CASCADE', max_length=20)),
                ('on_update', models.CharField(default='CASCADE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('engine', models.CharField(default='mysql', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('row_count', models.BigIntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VirtualTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('row_count', models.BigIntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('indexes', models.JSONField(blank=True, default=list)),
                ('primary_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
