# Generated by Django 5.2.10 on 2026-05-21 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualdatabase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_databases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='virtualtable',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tables.virtualdatabase'),
        ),
        migrations.AddField(
            model_name='tablerelationship',
            name='source_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='tables.virtualtable'),
        ),
        migrations.AddField(
            model_name='tablerelationship',
            name='target_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relations', to='tables.virtualtable'),
        ),
        migrations.AlterUniqueTogether(
            name='tablerelationship',
            unique_together={('source_table', 'source_column', 'target_table', 'target_column')},
        ),
    ]
