# Generated by Django 5.2.10 on 2026-05-21 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('raw_sql', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('team', 'Team'), ('organization', 'Organization'), ('public', 'Public')], default='private', max_length=20)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('relation_ids', models.CharField(blank=True, max_length=255)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('frequency', models.CharField(default='monthly', max_length=50)),
                ('viewed_by', models.CharField(default='private', max_length=50)),
                ('viewer_ids', models.CharField(blank=True, max_length=255)),
                ('authentication_type', models.CharField(default='user', max_length=50)),
                ('authentication_token', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
