# Generated by Django 5.2.10 on 2026-05-21 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('subscription', 'Subscription'), ('query', 'Query'), ('maintenance', 'Maintenance'), ('security', 'Security')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('action_label', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
